//  SECTIONS ACTIONS
export const
    FETCH_SECTIONS_BEGIN = 'FETCH_SECTIONS_BEGIN',
    FETCH_SECTIONS_SUCCESS = 'FETCH_SECTIONS_SUCCESS',
    FETCH_SECTIONS_FAILURE = 'FETCH_SECTIONS_FAILURE',
    SET_CURRENT_SECTION = 'SET_CURRENT_SECTION';