//  THREADS ACTIONS
export const
    FETCH_THREADS_BEGIN = 'FETCH_THREADS_BEGIN',
    FETCH_THREADS_SUCCESS = 'FETCH_THREADS_SUCCESS',
    FETCH_THREADS_FAILURE = 'FETCH_THREADS_FAILURE',
    SET_CURRENT_THREAD = 'SET_CURRENT_THREAD',
    ADD_THREADS_BEGIN = 'ADD_THREADS_BEGIN',
    ADD_THREADS_SUCCESS = 'ADD_THREADS_SUCCESS',
    ADD_THREADS_FAILURE = 'ADD_THREADS_FAILURE'
;